name: Deploy Java Spring app to render.com (Ex3.2)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: shamaanikala/spring-example

      - name: Deploy render.com
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.RENDER_COM_DEPLOY_HOOK }}
          method: 'GET'
